# Generated by Django 3.0.6 on 2020-05-17 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_Locker',
            fields=[
                ('cust_lock_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('contacted', models.CharField(choices=[('No Contact', 'No Contact'), ('Initial Contact', 'Initial Contact'), ('Second Contact', 'Second Contact')], default='No', max_length=50, verbose_name='Contacted')),
                ('renew_date', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Customer Locker',
                'verbose_name_plural': 'Customer Lockers',
                'ordering': ['locker_id__location_id__location_name', 'cust_id__cust_l_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('cust_l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('cust_email', models.EmailField(default='', max_length=100, verbose_name='Email')),
                ('cust_phone', models.CharField(default='', max_length=50, verbose_name='Phone #1')),
                ('cust_phone2', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone #2')),
                ('cust_address', models.CharField(default='', max_length=50, verbose_name='Street Address')),
                ('cust_city', models.CharField(max_length=50, verbose_name='City')),
                ('cust_state', models.CharField(max_length=50, verbose_name='State')),
                ('cust_zip', models.CharField(max_length=10, verbose_name='Zip Code')),
            ],
            options={
                'ordering': ['cust_l_name'],
            },
        ),
        migrations.CreateModel(
            name='Key_Status',
            fields=[
                ('key_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_status_name', models.CharField(max_length=100, verbose_name='Key Status Name')),
            ],
            options={
                'verbose_name': 'Key Status',
                'verbose_name_plural': 'Key Statuses',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('location_zip', models.CharField(blank=True, max_length=10, verbose_name='Location Zip')),
                ('location_capacity', models.IntegerField(default=0, verbose_name='Location Capacity')),
            ],
            options={
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('locker_id', models.AutoField(primary_key=True, serialize=False)),
                ('locker_name', models.CharField(max_length=100, verbose_name='Locker Name')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Locker_Status',
            fields=[
                ('locker_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('locker_status_name', models.CharField(max_length=100, verbose_name='Locker Status Name')),
            ],
            options={
                'verbose_name': 'Locker Status',
                'verbose_name_plural': 'Locker Statuses',
            },
        ),
        migrations.CreateModel(
            name='Locker_Usage',
            fields=[
                ('locker_usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('lu_description', models.CharField(max_length=100, verbose_name='Locker Usage')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_Status',
            fields=[
                ('main_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_status_name', models.CharField(max_length=100, verbose_name='Maintenance Status Name')),
            ],
            options={
                'verbose_name': 'Maintenance Status',
                'verbose_name_plural': 'Maintenance Statuses',
            },
        ),
        migrations.CreateModel(
            name='Maintenance_Type',
            fields=[
                ('main_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Maintenance Type')),
                ('main_type_name', models.CharField(max_length=100, verbose_name='Maintenance Type Name')),
                ('main_type_desc', models.CharField(max_length=100, verbose_name='Maintenance Type Description')),
            ],
            options={
                'verbose_name': 'Maintenance Type',
                'verbose_name_plural': 'Maintenance Types',
            },
        ),
        migrations.CreateModel(
            name='Renewal_Form',
            fields=[
                ('renewal_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-mail')),
                ('name_lease', models.CharField(default='', max_length=50, verbose_name='Name On Lease')),
                ('mailing_address', models.CharField(default='', max_length=300, verbose_name='Current Mailing Address')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Phone')),
                ('location', models.CharField(default='', max_length=50, verbose_name='Location')),
                ('locker_number', models.CharField(default='', max_length=50, verbose_name='Locker Number')),
                ('locker_usage', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3+', '3+')], max_length=50, verbose_name='Locker Usage')),
                ('renewal_decision', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='Renewal Decision')),
                ('feedback', models.TextField(default='', max_length=5000, verbose_name='Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Renewal_Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_description', models.CharField(max_length=100, verbose_name='Response Description')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('staff_l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('staff_email', models.EmailField(default='', max_length=100, verbose_name='Email')),
                ('staff_phone', models.CharField(default='', max_length=50, verbose_name='Phone #1')),
                ('staff_phone2', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone #2')),
                ('staff_address', models.CharField(default='', max_length=50, verbose_name='Street Address')),
                ('staff_city', models.CharField(max_length=50, verbose_name='City')),
                ('staff_state', models.CharField(max_length=50, verbose_name='State')),
                ('staff_zip', models.CharField(max_length=10, verbose_name='Zip Code')),
            ],
            options={
                'ordering': ['staff_l_name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100, verbose_name='Status Name')),
                ('status_desc', models.CharField(blank=True, max_length=100, verbose_name='Status Description')),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('waitlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('waitlist_date', models.DateField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('locations', models.ManyToManyField(to='database.Location')),
            ],
            options={
                'verbose_name': 'Waitlist',
                'verbose_name_plural': 'Waitlists',
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('renewal_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_date', models.DateField(blank=True)),
                ('sent_date_2', models.DateField(blank=True)),
                ('phone_call_date', models.DateField(blank=True, default=datetime.datetime(2020, 5, 17, 1, 56, 51, 814184, tzinfo=utc), verbose_name='Phone Call Date')),
                ('cust_locker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Cust_Locker')),
                ('response_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response1', to='database.Renewal_Response')),
                ('response_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response2', to='database.Renewal_Response')),
                ('response_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response3', to='database.Renewal_Response')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_scope', models.CharField(choices=[('General Facility', 'General Facility'), ('Specific Locker(s)', 'Specific Locker(s)')], max_length=50, verbose_name='Maintenance Scope')),
                ('maintenance_description', models.CharField(default='', max_length=250, verbose_name='Maintenance Description')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Location')),
                ('lockers', models.ManyToManyField(blank=True, to='database.Locker')),
                ('main_status_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Maintenance_Status')),
                ('main_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Maintenance_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Locker_Log',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locker_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=500, verbose_name='Action')),
                ('action_done', models.CharField(blank=True, max_length=500, verbose_name='Action Done')),
                ('next_step', models.CharField(blank=True, max_length=500, verbose_name='Action')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Location')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Staff')),
            ],
            options={
                'verbose_name': 'Locker Log',
                'verbose_name_plural': 'Locker Logs',
            },
        ),
        migrations.AddField(
            model_name='locker',
            name='locker_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Locker_Status'),
        ),
        migrations.CreateModel(
            name='Location_Renewals',
            fields=[
                ('location_renew_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True, verbose_name='Locker Location Renewal Date')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Location')),
            ],
            options={
                'verbose_name': 'Locker Location Renewal Date',
                'verbose_name_plural': 'Locker Location Renewal Dates',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100, verbose_name='Key Name')),
                ('key_status_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Key_Status')),
                ('locker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Locker')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry_date', models.DateField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('locations', models.ManyToManyField(to='database.Location')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Status'),
        ),
        migrations.CreateModel(
            name='Cust_Status',
            fields=[
                ('cust_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_status_date', models.DateField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Status')),
            ],
            options={
                'verbose_name': 'Customer Status',
                'verbose_name_plural': 'Customer Statuses',
            },
        ),
        migrations.AddField(
            model_name='cust_locker',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
        ),
        migrations.AddField(
            model_name='cust_locker',
            name='location_renewal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Location_Renewals'),
        ),
        migrations.AddField(
            model_name='cust_locker',
            name='locker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Locker'),
        ),
    ]
