# Generated by Django 3.0.6 on 2020-05-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200520_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locker_Usage',
        ),
        migrations.DeleteModel(
            name='Renewal',
        ),
        migrations.DeleteModel(
            name='Renewal_Response',
        ),
    ]
